apiVersion: k8s.mariadb.com/v1alpha1
kind: MariaDB
metadata:
  name: wordpress-mariadb
  namespace: wordpress
spec:
  rootPasswordSecretKeyRef:
    name: mariadb-secret
    key: root-password
    generate: false
  image: docker.io/library/mariadb:11.4
  port: 3306
  storage:
    size: 5Gi
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi
