apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../../base
  - namespace.yaml
  - dragonfly.yaml
  - hpa.yaml

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: backend-config
  - path: deployment-patch.yaml
    target:
      kind: Deployment
      name: backend
