apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: development

resources:
  - ../../base
  - namespace.yaml
  - dragonfly.yaml

patches:
  - path: configmap-patch.yaml
    target:
      kind: ConfigMap
      name: backend-config
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: backend
      spec:
        replicas: 1
    target:
      kind: Deployment
      name: backend
