apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: sasha543/course-app:1
          ports:
            - containerPort: 8088
          envFrom:
            - configMapRef:
                name: backend-config
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8088
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /readyz
              port: 8088
            initialDelaySeconds: 5
            periodSeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
